# Shell
$(pwd)/zsh/.zshrc:$HOME/.zshrc
$(pwd)/starship/starship.toml:$HOME/.config/starship/starship.toml

# Terminal
$(pwd)/warp/settings.toml:$HOME/.warp/settings.toml

# Editor
$(pwd)/cursor/settings.json:$HOME/Library/Application Support/Cursor/User/settings.json

# AI coding tools
$(pwd)/claude-code/settings.json:$HOME/.claude/settings.json

# Terminal file manager
$(pwd)/yazi:$HOME/.config/yazi
